# GitHub CI build pipeline
name: Transformer CI build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: Run Unit Tests and generate coverage report
      run: |
        pytest
        coverage run -m unittest
        coverage report
        coverage html
    - name: Archive code coverage html report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: src/htmlcov
    - name: Run package creation
      run: |
        python -m pip install --user --upgrade build
        python -m build
    # - name: Archive package
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: transformers
    #     path: dist
    - name: "Build & test"
      run: |
          echo "done!"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: v0.1.0
        files: |
          dist/